const HELP_BY_LABEL: Record<string, string> = {
    'use rss from bag build research etc': 'Uses resource items from the bag when the bot needs resources for tasks such as building, research, Anima, or Lunite.',
    'use vip points': 'Uses VIP Point items from the bag.',
    'use exp items': 'Uses EXP and EXP boost items from the bag.',
    'open all chests': 'Opens chest items from the bag and shows received items in the log.',
    'use star scrolls': 'Uses Star Scrolls to upgrade the currently equipped castle when there are enough scrolls for a 100% upgrade chance.',
    'put gems in treasure trove 30 days': 'Deposits gems into Treasure Trove for 30 days and collects them when the timer is due.',
    'other login reconnect time seconds': 'Wait time before reconnecting after another login is detected. The value is in seconds.',

    'mystery box': 'Collects mystery boxes when they appear, roughly every 15 minutes.',
    'turf quests': 'Collects active turf quests.',
    'admin quests': 'Completes Admin quests automatically when possible, otherwise processes them one by one.',
    'guild quests': 'Completes Guild quests automatically when possible, otherwise processes them one by one.',
    'vip quests': 'Collects VIP quest chests as they appear.',
    'daily login gifts': 'Collects the daily login gift from the 21-day rewards table.',
    'adventure log': 'Completes Adventure Log quests automatically.',
    'open all guild quests': 'Uses Guild quest scrolls from the bag and completes them until the reserve amount is reached.',
    'open all admin quests': 'Uses Admin quest scrolls from the bag and completes them until the reserve amount is reached.',
    'quest reserve': 'Amount of Admin/Guild scrolls to keep before the bot stops opening quest scrolls.',

    'use speed ups': 'Enables speed-up handling. Other speed-up options do not run while this is off.',
    'use normal speeds only for building': 'Restricts normal/general speed-up items to building and construction tasks only.',
    'wait for help': 'Waits for the help bar before using speed-ups on building or research. This only works reliably in the guild home kingdom.',
    'max speed excess': 'Limits how much speed-up time can be wasted when speeding a queue.',
    'building': 'Allows speed-up usage on building queues.',
    'research': 'Allows speed-up usage on research queues.',
    'training': 'Allows speed-up usage on troop training queues.',
    'healing': 'Allows speed-up usage on healing queues.',
    'traps': 'Allows speed-up usage on trap construction queues.',
    'trap repair': 'Allows speed-up usage on trap repair queues.',
    'pact merging': 'Allows speed-up usage on pact merging queues.',
    'wall repair': 'Allows speed-up usage on wall repair queues.',
    'gear': 'Allows speed-up usage on equipment-related queues.',
    'lunar gear': 'Allows speed-up usage on Lunar Gear queues.',

    'attack labyrinth': 'Attacks Labyrinth and logs winnings and attempts left. It can also use Holy Star items from the bag.',
    'use holy star items': 'Uses Holy Star items from the bag for Labyrinth.',
    'attack kingdom tycoon': 'Attacks Kingdom Tycoon and logs winnings and attempts left. It can also use Luck Token items from the bag.',
    'use luck tokens': 'Uses Luck Token items from the bag for Kingdom Tycoon.',
    'only use free attempt': 'Prevents spending Holy Stars or Luck Tokens and uses only free daily attempts.',
    'only use free attempt?': 'Prevents spending event items and uses only free daily attempts.',

    'send help': 'Sends guild help automatically. The check delay controls how often the bot looks for helps.',
    'request help': 'Requests help for ongoing construction and research tasks.',
    'collect guild gifts': 'Collects unopened guild gifts and deletes opened gifts so the account can keep collecting.',
    'collect fortune packets': 'Collects guild fortune packets during the guild fortune event.',
    'slow help speed when bar full': 'Slows guild help checks after the guild coin bar is full so other guild members can fill their bars.',
    'join guild showdown': 'Joins Guild Showdown when active, using the best available heroes, troops, familiars, and leader.',
    'check helps every': 'Cooldown in seconds between guild help checks.',
    'check gifts every': 'Cooldown in seconds between guild gift checks.',

    'food boost': 'Automatically activates the selected turf production boost when useful.',
    'stone boost': 'Automatically activates the selected turf production boost when useful.',
    'wood boost': 'Automatically activates the selected turf production boost when useful.',
    'ore boost': 'Automatically activates the selected turf production boost when useful.',
    'gold boost': 'Automatically activates the selected turf production boost when useful.',
    'gathering boost': 'Automatically activates gathering boost items when useful.',
    'reduce upkeep': 'Automatically activates reduced upkeep items when useful.',
    'daily missions': 'Enables completion of in-game daily missions for battle pass and Technolabe progress.',
    'send emojis': 'Completes the daily mission that requires sending emojis.',
    'shelter': 'Completes the daily mission related to sheltering.',
    'labyrinth': 'Completes the daily mission related to Labyrinth.',
    'kingdom tycoon': 'Completes the daily mission related to Kingdom Tycoon.',

    'always shielded': 'Keeps the account shielded. Redeploy time controls when a new shield is applied before the old one expires.',
    'redeploy randomize time minutes': 'Randomizes shield redeploy timing by the configured number of minutes.',
    'redeploy shield when time left is around': 'Threshold for replacing an active shield before it expires.',
    'use longer shields first': 'Uses the longest shield items first instead of the shortest ones.',
    'shield when rallied': 'Deploys a shield when a rally starts marching on the castle.',
    'shield when scouted': 'Deploys a shield when another player scouts the castle.',
    'shield when under attack': 'Deploys a shield when another player attacks the castle.',
    'always anti scout': 'Keeps Anti-Scout active on the account.',
    'anti scout when scouted': 'Deploys Anti-Scout when another player scouts the account.',
    'use longer anti scout first': 'Uses the Anti-Scout item with the most time first.',
    'redeploy anti scout when time left is around': 'Threshold for replacing Anti-Scout before it expires.',
    'recall gathering troops if attacked': 'Recalls gathering troops if their resource tile is attacked.',
    'recall gathering troops if scouted': 'Recalls gathering troops when their resource tile is scouted.',
    'recall gathering troops on conflict': 'Recalls troops when another player is marching toward the same tile.',
    'time to wait before regathering in minutes': 'Wait time before sending gatherers again after a tile attack, scout, or conflict.',
    'recall sheltered troops after attack': 'Shelters during an attack and releases troops after the attack finishes.',
    'dont shelter siege': 'Excludes siege troops from sheltering so more important troops are prioritized.',
    'preferred shield': 'Selects which shield type the bot should prefer when applying shields.',
    'shelter mode': 'Selects how the bot fills shelter, such as leader with one troop or leader with best troops.',

    'gather resources': 'Enables automatic resource gathering. Gathering settings are ignored while this is off.',
    'leave spare army': 'Leaves one or more armies free for hunting or other actions instead of sending all armies to gather.',
    'spare army amount': 'Number of armies to keep free while gathering.',
    'max armies to gather 0 for all': 'Maximum armies allowed for gathering. Set to 0 to use all possible armies.',
    'target higher level tiles first': 'Prioritizes higher-level tiles over closer tiles.',
    'gather lowest amount first': 'Prioritizes the resource type with the lowest castle stock among selected resource types.',
    'ignore level settings for gems': 'Allows any level of gem lode regardless of selected gathering levels.',
    'only gather clearable tiles': 'Skips tiles the account cannot fully clear with available troops.',
    'recall camps automatically': 'Recalls camped armies if a target tile disappears while a march is walking.',
    'use gathering gear': 'Equips gathering gear before sending marches and delays other gear swaps until armies land.',
    'search multiplier area': 'Increases the search area around the castle.',
    'max travel time minutes': 'Skips gathering tiles farther than this travel time.',
    'sending delay seconds': 'Delay between sending each gathering march.',
    'minimum tile resources': 'Minimum resources left on a tile before the bot will gather it. Does not apply to gem lodes.',
    'enable gather schedule': 'Limits gathering to the configured same-day time window.',
    'start time': 'Start time for the gathering schedule.',
    'end time': 'End time for the gathering schedule.',

    'auto send to name': 'Player name to receive resources. It must match the in-game name exactly, including case and spacing.',
    'max travel time seconds': 'Maximum travel time allowed before sending resources or hunting targets.',
    'supply speed': 'Minimum delay between supply marches.',
    'supply speed 001 099': 'Minimum delay between supply marches. Event kingdoms may override this.',
    'use speed gear': 'Uses speed gear while sending supply marches.',
    'auto send resources': 'Enables sending resources according to reserve and threshold settings.',
    'send bag resources': 'Allows sending resources from bag items using the bag reserve values.',
    'reserved amount': 'Amount of the resource to keep in the castle or bag.',
    'threshold': 'Minimum resource amount required before supply marches begin sending.',
    'food': 'Enables this resource type for the current resource table.',
    'stone': 'Enables this resource type for the current resource table.',
    'wood': 'Enables this resource type for the current resource table.',
    'ore': 'Enables this resource type for the current resource table.',
    'gold': 'Enables this resource type for the current resource table.',
    'gems': 'Enables gem lodes for gathering when gathering targets are configured.',

    'exchange cargo ship items': 'Enables automatic Cargo Ship trading.',
    'only trade for resource items': 'Trades only for resource items and ignores non-resource rewards such as speed-ups or Star Scrolls.',
    'use resources from bag if needed': 'Uses resources from the bag for Cargo Ship trades when needed.',
    'minimum item stars': 'Minimum Cargo Ship item star rating required before the bot will trade. Valid range is 1 to 3.',

    'auto research': 'Starts research automatically when no research is already in progress.',
    'use target system': 'Researches targeted research and prerequisites instead of only following full tree order.',
    'use technolabes': 'Uses Technolabes to instantly complete research without resource cost. Event points are not gained this way.',
    'minimum might': 'Minimum research might required before Technolabes are used.',

    'enable schedule system': 'Applies the defined offline/online schedule.',
    'recall armies': 'Recalls armies before scheduled offline mode.',
    'monitor shield': 'Checks shield before going offline and renews it if it would expire during offline time.',
    'monitor anti scout': 'Checks Anti-Scout before going offline and renews it if it would expire during offline time.',
    'monitor shelter': 'Checks sheltered troops and logs in to re-shelter if the timer would expire while offline.',
    'randomize schedule': 'Adds randomization to schedule timing.',
    'random max minutes': 'Maximum randomization window for schedule timing.',
    'offline time go offline at': 'Time of day when the account should go offline.',
    'online time come back at': 'Time of day when the account should come back online.',
    'stay online for hhmm': 'In interval mode, how long to remain online before going offline.',
    'then offline for hhmm': 'In interval mode, how long to remain offline before returning online.',

    'auto build': 'Allows the bot to build automatically.',
    'auto upgrade': 'Allows the bot to upgrade buildings automatically.',
    'build by lowest level': 'Targets lower-level buildings first.',
    'lowest level first': 'Targets lower-level buildings first.',
    'building priority': 'Prioritizes selected building categories such as Castle, Academy, resource buildings, or no priority.',
    'max build level': 'Caps the maximum building level the bot is allowed to upgrade to.',

    'auto train troops': 'Enables automatic troop training.',
    'rotate training': 'Cycles through selected troop types for training.',
    'auto heal troops': 'Automatically heals troops in the infirmary.',
    'auto heal sanctuary': 'Automatically heals sanctuary troops in chunks.',
    'recall troops for skirmish': 'Recalls troops from shelter or gathering to attack turf skirmishes.',

    'auto switch gear': 'Automatically changes gear for actions such as gathering, training, building, research, familiars, and Lunar Gear.',
    'auto switch gears': 'Automatically changes gear for actions such as gathering, training, building, research, familiars, and Lunar Gear.',
    'auto upgrade gear': 'Upgrades equipment quality when required materials are available.',
    'auto craft gear': 'Crafts selected equipment when required materials are available.',
    'use cabinet expander': 'Uses cabinet expander items when cabinet space is full.',
    'idle gear timer seconds': 'Delay before switching to the idle gear set after other gear actions finish.',
    'idle gear time': 'Delay before switching to the selected idle gear set after another gear action finishes.',
    'idle gear': 'Gear set used while the account is not performing another gear-specific action.',

    'hire new heroes': 'Hires new heroes when enough medals are available.',
    'use hero exp items': 'Uses hero EXP items, prioritizing higher-level heroes first.',
    'upgrade heroes': 'Upgrades hero color when enough medals are available.',
    'enhance heroes': 'Equips hero items and raises hero rank.',
    'revive dead leader': 'Uses revival fruit, or buys it if gem spending is enabled, to revive a dead leader.',
    'auto attack hero stages': 'Starts attacking hero stages automatically.',
    'use braveheart items': 'Uses Braveheart items from inventory when stamina is empty.',
    'sweep stage': 'Uses sweep on eligible hero stages instead of manually fighting the stage.',
    '10x sweep': 'Uses 10x sweep when available for faster hero stage runs.',
    'use priority mode': 'Uses the configured hero stage priority rules while attacking stages.',
    'hero selection': 'Controls how heroes are selected for the action.',
    'chapter flow': 'Sequential mode progresses from the current stage; custom mode targets a specific unlocked stage.',
    'sequential stage type': 'Selects whether sequential hero stage attacks use Normal or Elite stages.',
    'chapter type': 'Selects the custom hero stage chapter type.',
    'chapter': 'Selects the custom hero stage chapter to attack.',
    'stage target': 'Targets all stages in the selected chapter or one specific stage.',
    'auto attack colosseum': 'Attacks Colosseum automatically when attempts are available.',
    'attack guild members': 'Allows Colosseum attacks against guild members.',
    'collect arena gems': 'Collects available Colosseum gem rewards.',
    'buy extra attempts': 'Allows buying extra Colosseum attempts.',
    'attack heroes': 'Selects which heroes are used to attack.',
    'defenders': 'Controls whether Colosseum defenders are left unchanged or auto-selected.',
    'attempts to buy': 'Number of extra Colosseum attempts to buy after current attempts are used.',
    'min win chance': 'Minimum simulated Colosseum win chance allowed before attacking.',
    'max win chance': 'Maximum simulated Colosseum win chance filter.',

    'save stats': 'Enables saving/exporting account statistics.',
    'save guild fest stats': 'Enables saving/exporting Guild Fest statistics.',
    'save guild list': 'Enables saving/exporting guild member list data.',
    'statistic settings': 'Configures stat point goals and final stat targets used by report exports.',
    'set reset time': 'Configures when saved gift/stat data resets. Use hourly intervals or a specific day and time.',
    'day based': 'Resets saved gift/stat data on the selected weekday at the selected time.',
    'hourly based': 'Resets saved gift/stat data after the selected hour/day interval, counted from the selected start time.',
    'day': 'Weekday used by day-based report reset timing.',
    'every': 'Interval used by hourly-based report reset timing.',
    'from': 'Start time used by hourly-based report reset timing.',
    'time': 'Time of day used by day-based report reset timing.',
    'final hunt goal': 'Final hunt stat target used by report/stat tracking.',
    'final purchase goal': 'Final purchase stat target used by report/stat tracking.',
    'hunt point goals': 'Per-level hunt point targets used by statistic/report tracking.',
    'purchase point goals': 'Per-level purchase point targets used by statistic/report tracking.',

    'join rallies darknest only': 'Allows the bot to join Darknest rallies. It does not join rallies against players or wonders.',
    'rally limit': 'Maximum number of armies the bot may use for joining Darknest rallies.',
    'maximum rally time': 'Maximum rally start timer the bot will join, useful for avoiding long fake rallies.',
    'dont join if lab is full': 'Skips Darknest rallies when the Dark Essence Lab is full.',
    'dont fill rally': 'Avoids sending enough troops to fill the rally to full capacity.',
    'dont send siege': 'Prevents siege troops from being sent to Darknest rallies.',
    'dont send t5': 'Prevents T5 troops from being sent to Darknest rallies.',
    'send one type': 'Sends only the strongest matching troop type based on the rally leader composition.',
    'add buffers': 'Adds small low-tier infantry, ranged, and cavalry buffers to reduce higher-tier infirmary losses.',
    'darknest levels to join': 'Selects which Darknest levels the bot is allowed to join.',
    'wait before rejoining minutes': 'How long to wait before rejoining a rally after troops are kicked or returned.',
    'troops to send': 'Controls whether the rally sends one troop or the highest available troops.',
    'send one troop': 'Sends one lowest-tier troop to the Darknest rally.',
    'send max troops with priority': 'Sends the highest eligible troops using the configured rally priority behavior.',
    'transmute dark essences': 'Transmutes Dark Essences in the lab automatically.',
    'keep one slot free': 'Keeps one Dark Essence Lab slot open when handling essences.',
    'delete essences lower than': 'Deletes Dark Essences below this level. Set 0 to avoid deleting essences.',

    'use high tier troops': 'Uses higher tier troops for realm gathering when available.',
    'kills per day': 'Daily monster kill target for realm monster hunting.',
    'lunite': 'Enables Lunite as a realm gathering resource target.',

    'use gems': 'Allows the bot to spend gems for enabled purchases.',
    'use guild coins': 'Allows the bot to spend guild coins for enabled purchases. Guild coins are prioritized over gems.',
    'shield 8h': 'Allows buying an 8-hour shield with guild coins when required.',
    'shield': 'Allows buying shield items when required. The selected duration is preferred, with lower options used if needed.',
    'withdraw squad': 'Allows buying Withdraw Squad items, usually used with gathering recall behavior.',
    'gold hammer': 'Allows buying Golden Hammers for construction needs.',
    'steel cuffs': 'Allows buying Steel Cuffs for building or research needs.',
    'soul crystal': 'Allows buying Soul Crystals when required.',
    'crystal pickaxe': 'Allows buying Crystal Pickaxes when required.',
    'war tome': 'Allows buying War Tomes when required.',
    'archaic tome': 'Allows buying Archaic Tomes when required.',
    'buy vip points up to level': 'Buys VIP points until the configured VIP level is reached. Set 0 to disable.',
    'reserve guild coins': 'Guild coin amount to keep reserved. The bot will not spend below this value.',

    'upgrade': 'Allows the bot to upgrade buildings automatically.',
    'ignore spam target': 'Ignores configured spam-build targets when choosing building actions.',
    'auto rent second queue': 'Automatically rents the second construction queue when available and allowed.',
    'second queue spam only': 'Restricts the second construction queue to spam-building work.',
    'strict priority': 'Follows the selected building priority more strictly when choosing upgrades.',
    'spam target type': 'Building group used for spam-building behavior.',
    'spam target building': 'Specific building used as the spam-build target.',
    'building target': 'Assigns each construction slot to the building type the bot should maintain.',
    'resource buildings': 'Targets for resource-field construction slots.',
    'military buildings': 'Targets for military building slots.',
    'familiar buildings': 'Targets for familiar building slots.',
    'reset build data': 'Resets queued or stored construction target data.',

    'train troops': 'Enables automatic troop training.',
    'rotate troop training': 'Rotates through selected troop types during training.',
    'heal troops': 'Automatically heals troops in the infirmary.',
    'heal sanctuary': 'Automatically heals sanctuary troops in chunks.',
    'craft luminous gear': 'Allows automatic crafting of Lunar/Luminous gear items.',
    'selected chapter': 'Chapter used for skirmish troop data and skirmish actions.',
    'attack skirmish levels': 'Automatically attacks turf skirmish levels.',
    'attack trail by fire': 'Automatically attacks Trial by Fire when enabled.',
    'attack skirmish when troops at': 'Minimum troop percentage required before attacking skirmishes.',
    'troop training': 'Troop targets used by automatic troop training.',
    'amount to train': 'Target amount to train for this troop row.',

    'hunt monsters': 'Automatically sends heroes to hunt monsters.',
    'sending delay ms': 'Delay in milliseconds between monster hunting marches.',
    'use energy items': 'Uses energy items from the bag to refill Energy for monster hunting.',
    'use winged boots on steal': 'Uses Winged Boots when trying to steal a monster or defend against a steal.',
    'send unfinished monsters to guild chat': 'Posts monster coordinates to guild chat if the bot cannot finish the monster.',
    'avoid conflict': 'Avoids monsters or tiles that would create a conflict with other players.',
    'also avoid guild': 'Also avoids conflict with guild members.',
    'use saberfang skill if possible': 'Uses Saberfang familiar skill when it is unlocked and available.',
    'hunt priority': 'Selects which monster condition to prioritize, such as any, full health, lowest health, or steal.',
    'levels to hunt': 'Selects which monster levels the bot is allowed to hunt.',
    'types to hunt': 'Selects monster defense types to hunt.',
    'magic and physical': 'Allows hunting monsters from both magical and physical groups.',
    'high mdef': 'Targets monsters with high magic defense.',
    'high pdef': 'Targets monsters with high physical defense.',
    'start hunt when energy is more than': 'Starts hunting when Energy is above this percentage.',
    'use combo prediction': 'Runs a test hit, predicts the required multiplier, then uses enough hits if Energy allows.',
    'stop after one kill': 'Stops the hunting run after one monster kill.',

    'pact settings': 'Controls opening and merging pacts for familiars.',
    'open pacts': 'Opens merged or obtained familiar pacts automatically, including newly unlocked familiars.',
    'merge pacts': 'Enables automatic pact merging for selected pact types.',
    'familiar data': 'Per-familiar training, enhancing, skill, and item-use settings.',
    'train skill': 'Continues training familiar skills when the familiar has reached max level.',
    'enhance': 'Enhances the familiar when required resources are available.',
    'upg skills': 'Upgrades familiar skills when enough runes or fragments are available.',
    'use exp': 'Uses familiar EXP items for this familiar.',
    'use skill': 'Allows supported familiar skills to be used automatically.',
    'rarity': 'Current familiar rarity value shown for tracking.',

    'collect rewards': 'Collects Guild Fest rewards automatically when available.',
    'complete missions': 'Allows the bot to take and complete selected Guild Fest missions.',
    'buy extra mission': 'Allows buying an extra Guild Fest mission attempt.',
    'send mail to player': 'Player name to notify by mail for Guild Fest mission handling.',
    'guild missions': 'Selects Guild Fest missions and their point thresholds for the active pool.',
    'guild task': 'Default Guild Fest task pool.',
    '120 missions': 'Solo 120% mission pool settings.',
    '200 missions': 'Solo 200% mission pool settings.',
    'min points': 'Minimum points required before the bot accepts or keeps this mission.',
    'max points': 'Maximum points allowed for this mission threshold.',
    'complete': 'Configures missions the bot should complete.',
    'delete': 'Configures missions the bot should delete or remove.',
}

export function normalizeHelpKey(label: string) {
    return label
        .toLowerCase()
        .replace(/&/g, 'and')
        .replace(/[^a-z0-9]+/g, ' ')
        .trim()
        .replace(/\s+/g, ' ')
}

export function getSettingHelp(label?: string, fallback?: string) {
    if (fallback) return fallback
    if (!label) return undefined
    const key = normalizeHelpKey(label)
    const mappedHelp = HELP_BY_LABEL[key]
    if (mappedHelp) return mappedHelp

    if (/^level \d+$/.test(key)) {
        return 'Point goal value for this level in statistic/report tracking.'
    }

    if (/^location \d+$/.test(key)) {
        return 'Construction slot target for this building location.'
    }

    if (/^pact \d+[ab]?$/.test(key)) {
        return 'Selects whether this pact type can be merged automatically.'
    }

    return `Controls the ${label} option.`
}
